apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: vintage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/hiraya-frontend:1ebec3729cd10fe1eeac6f0858fba58e2da07956
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: vintage
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: ClusterIP

