apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: vintage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 549475122024.dkr.ecr.ap-northeast-1.amazonaws.com/hiraya-order-service:f357b9913476d9efac4587aca10c6218875830e8
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3004"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vintage-secrets
                  key: ORDERS_DB_URL
            - name: AUTH_SERVICE_URL
              value: "http://auth:3002"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3003"

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: vintage
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP
