apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vintage-services
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - vintage
  selector:
    matchLabels:
      app: gateway   
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
