provider:
  name: aws

sources:
  - gateway-httproute

policy: sync
registry: txt
txtOwnerId: hiraya-dev-eks
domainFilters:
  - hiraya.noidilin.dev
triggerLoopOnEvent: true

serviceAccount:
  create: true
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::549475122024:role/devops-hiraya-dev-eks-external-dns
