apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.className | quote }}
  infrastructure:
    parametersRef:
      group: gateway.k8s.aws
      kind: LoadBalancerConfiguration
      name: {{ .Values.gateway.name }}-alb
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              {{ .Values.allowedRoutes.namespaceLabelKey | quote }}: {{ .Values.allowedRoutes.namespaceLabelValue | quote }}
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              {{ .Values.allowedRoutes.namespaceLabelKey | quote }}: {{ .Values.allowedRoutes.namespaceLabelValue | quote }}
