apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: {{ .Values.gateway.name }}-alb
  namespace: {{ .Release.Namespace }}
spec:
  loadBalancerName: {{ .Values.loadBalancer.name | quote }}
  scheme: internet-facing
  listenerConfigurations:
    - protocolPort: HTTPS:443
      defaultCertificate: {{ .Values.loadBalancer.certificateArn | quote }}
