apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: {{ .Values.gateway.name }}-target-group
  namespace: {{ .Release.Namespace }}
spec:
  defaultConfiguration:
    targetType: {{ .Values.targetGroup.targetType | quote }}
