apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vintage-secrets
  namespace: vintage
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: hiraya-dev-secrets-manager
  target:
    name: vintage-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: /hiraya/dev/apps/vintage
