import type { ArchitectureRuntimeInteractionsContent } from './architectureRuntimeInteractions'

export const architectureRuntimeInteractionsContentZhTW: ArchitectureRuntimeInteractionsContent = {
  routeId: 'arch',
  title: '讓 traffic、services 與 secrets 留在正確邊界',
  summary: '當 ownership 與 exposure 已經清楚後，這個視圖說明 public Storefront、private services 與 materialized runtime secrets 如何互動，而不是把每個 boundary 都公開。',
  chrome: {
    eyebrow: 'Runtime interaction',
    tabs: { 'request-paths': 'Request paths', 'secret-materialization': 'Secret materialization' },
    statusLabels: { active: 'active', legacy: 'legacy', data: 'data', 'platform-support': 'platform support' },
    serviceBoundaryDefaultContext: 'service boundary',
    frontendBoundaryContext: 'frontend boundary behavior',
    kubernetesLabel: 'Kubernetes',
    portLabel: 'Port',
    exposureLabel: 'Exposure',
    notApplicableLabel: 'n/a',
    requestGraphEyebrow: 'flow graph',
    requestGraphKicker: 'same-origin → private services',
    requestGraphTitle: '一條 visitor path，分支到多個 private services',
    requestGraphDescription: 'Storefront visitor traffic 只到達 Storefront route；API requests 先經過 Storefront proxy 與 gateway，再選擇 private services。',
    secretGraphEyebrow: 'materialization flow',
    secretGraphKicker: 'external source → runtime secret → pods',
    secretGraphTitle: 'Secrets 以 reference 移動，而不是把 values 複製進 Git',
    secretGraphDescription: 'Hover node 可檢視每個 materialization handoff 背後的 owner、mechanism 與 source reference。',
    nonClaimsEyebrow: 'non-claims',
    nonClaimsTitle: '這張圖沒有聲稱的事',
  },
  defaultTabId: 'request-paths',
  facts: [
    { label: 'Region', value: 'ap-northeast-1', note: 'Disposable dev platform region。' },
    { label: 'AZs', value: '3', note: 'Public edge 與 private workload subnets 橫跨三個 availability zones。' },
    { label: 'Public routes', value: 'Storefront + Argo CD + Grafana', note: 'Storefront user route 與 dev ops review surfaces 共用 public edge。' },
    { label: 'Private service pattern', value: 'ClusterIP', note: 'Backends 與 data services 留在 Kubernetes service discovery 內。' },
  ],
  requestPaths: {
    title: 'Request paths 在 gateway 進入 private services 前維持 same-origin',
    summary: 'Browser 先到 shared public edge 與 Storefront。Static assets 停在 nginx；API calls 則透過 Storefront proxy 進到 private gateway 與被選定的 service boundary。',
    stages: [
      { id: 'browser', label: 'Browser', boundary: 'public-internet', mechanism: 'HTTPS visitor session', description: 'Visitor 只知道 Storefront origin 與 path，不知道 private service DNS names。' },
      { id: 'public-edge', label: 'Route 53 / ALB / Gateway API / HTTPRoute', boundary: 'public-edge', mechanism: 'shared public edge', description: 'DNS、TLS、load balancing、Gateway 與 HTTPRoute 發佈被選定的 hostnames 和 routes。' },
      { id: 'storefront', label: 'Hiraya Furugi Storefront', boundary: 'application-runtime', mechanism: 'frontend Service on port 3000 → nginx on 80', description: 'Public application entry 服務 demo Storefront，並讓 browser API calls 保持 same-origin。' },
      { id: 'static-assets', label: 'nginx static assets', boundary: 'application-runtime', mechanism: 'static file response', description: '一般頁面 assets 由 frontend container 回應，不進入 backend services。' },
      { id: 'api-proxy', label: 'Storefront /api proxy', boundary: 'application-runtime', mechanism: 'same-origin /api path', description: 'API traffic 透過受控 proxy path 離開 public Storefront boundary，而不是 browser 直接呼叫 backends。' },
      { id: 'gateway', label: 'gateway', boundary: 'application-runtime', mechanism: 'ClusterIP service on 3001', description: 'Private gateway 依 /api/auth、/api/products、/api/orders、/api/users 選擇 backend service。' },
      { id: 'auth', label: 'auth', boundary: 'application-runtime', mechanism: 'ClusterIP service on 3002', description: '在 gateway 後方處理 login、registration 與 authentication responses。' },
      { id: 'product-service', label: 'product-service', boundary: 'application-runtime', mechanism: 'ClusterIP service on 3003', description: '提供 Hiraya Furugi Catalog API 給 browsing 與 product detail requests。' },
      { id: 'orders', label: 'orders', boundary: 'application-runtime', mechanism: 'ClusterIP service on 3005', description: '擁有 active Storefront order-history 與 checkout API path。' },
      { id: 'vintage-postgres', label: 'vintage-postgres', boundary: 'private-data', mechanism: 'StatefulSet + Headless Service + PVC on 5432', description: 'Authentication、catalog、user 與 order data 的 internal dev data component。' },
    ],
    examples: [
      { id: 'catalog-browsing', label: 'Catalog browsing', path: '/api/products', stages: ['browser', 'public-edge', 'storefront', 'api-proxy', 'gateway', 'product-service', 'vintage-postgres'], claim: 'Product reads 先經 Storefront origin 與 gateway，才到 private catalog service。' },
      { id: 'authentication', label: 'Authentication', path: '/api/auth/*', stages: ['browser', 'public-edge', 'storefront', 'api-proxy', 'gateway', 'auth', 'vintage-postgres'], claim: 'Login 與 registration 透過 private gateway 路由到 auth，不以 public services 暴露。' },
      { id: 'checkout-history', label: 'Checkout / order history', path: '/api/orders/*', stages: ['browser', 'public-edge', 'storefront', 'api-proxy', 'gateway', 'orders', 'vintage-postgres'], claim: 'Active Storefront order contract 由 private gateway path 後方的 orders 擁有。' },
    ],
  },
  serviceBoundaries: {
    title: 'Service boundaries 說明哪些元件參與 Storefront path',
    summary: '每張 card 命名 runtime responsibility、Kubernetes shape、exposure mode，以及 portfolio-relevant service 如何參與 Storefront path。',
    services: [
      { id: 'frontend', name: 'frontend', status: 'active', responsibility: '服務 Hiraya Furugi Storefront 與 same-origin /api proxy entry。', kubernetesType: 'Deployment + Service + HTTPRoute', port: '3000 → 80', exposure: 'Public via HTTPRoute attached to the shared Gateway.', participatesIn: ['Storefront pages', 'static assets', '/api proxy'], notes: 'Service 是 ClusterIP；public route 透過 Gateway API，而不是 service LoadBalancer。' },
      { id: 'gateway', name: 'gateway', status: 'active', responsibility: '聚合 private services 的 backend API routing。', kubernetesType: 'Deployment + Service', port: '3001', exposure: 'ClusterIP', participatesIn: ['/api/auth/*', '/api/products', '/api/orders/*', '/api/users/*'] },
      { id: 'auth', name: 'auth', status: 'active', responsibility: '處理 login、registration 與 authentication responses。', kubernetesType: 'Deployment + Service', port: '3002', exposure: 'ClusterIP', participatesIn: ['/api/auth/*'] },
      { id: 'product-service', name: 'product-service', status: 'active', responsibility: '擁有 Hiraya Furugi Catalog API，提供 product browsing 與 detail data。', kubernetesType: 'Deployment + Service', port: '3003', exposure: 'ClusterIP', participatesIn: ['/api/products', 'orders product lookup'] },
      { id: 'orders', name: 'orders', status: 'active', responsibility: '擁有 active Storefront checkout 與 order-history API contract。', kubernetesType: 'Deployment + Service', port: '3005', exposure: 'ClusterIP', participatesIn: ['/api/orders', '/api/orders/my-orders'], notes: '這個 dev contract 仍讓部分 order ownership behavior 維持 client-gated，因此 production-grade authorization 仍是 hardening item。' },
      { id: 'vintage-postgres', name: 'vintage-postgres', status: 'data', responsibility: '保存 authentication、catalog、users 與 orders 的 disposable dev data。', kubernetesType: 'StatefulSet + Headless Service + PVC', port: '5432', exposure: 'Private headless service', participatesIn: ['runtime database access'], notes: '對 rebuildable dev platform 有用；不是 production HA database claim。' },
    ],
  },
  secretMaterialization: {
    title: 'Secrets 在 Git 中只被 reference，並在 runtime materialize',
    summary: 'GitOps 擁有 ExternalSecret 與 store reference。AWS Secrets Manager 保存 secret source，External Secrets Operator 透過 IRSA 讀取，Kubernetes 取得 operator-owned runtime Secret 供 pods 使用。',
    steps: [
      { id: 'aws-secrets-manager', label: 'AWS Secrets Manager', owner: 'AWS Foundation', mechanism: 'allowlisted secret source', explanation: 'Durable Vintage runtime secret source 存在 Git 之外，透過名稱讀取，而不是複製進 manifests。', sourceRef: '/hiraya/dev/apps/vintage' },
      { id: 'irsa-reader', label: 'External Secrets Operator IRSA', owner: 'Cluster Platform + AWS IAM', mechanism: 'AssumeRoleWithWebIdentity + read-only policy', explanation: 'external-secrets service account 只能 describe/read allowlisted Secrets Manager ARNs。', sourceRef: 'system:serviceaccount:external-secrets:external-secrets' },
      { id: 'cluster-secret-store', label: 'ClusterSecretStore', owner: 'Cluster Platform', mechanism: 'AWS Secrets Manager provider in ap-northeast-1', explanation: 'Shared store 告訴 External Secrets Operator 要使用哪個 provider、region 與 service account contract。', sourceRef: 'hiraya-dev-secrets-manager' },
      { id: 'external-secret', label: 'ExternalSecret', owner: 'Application Runtime GitOps', mechanism: 'vintage/vintage-secrets with refreshInterval: 1h', explanation: 'Application manifest reference ClusterSecretStore 與 source path，並要求 operator 擁有 target Secret。', sourceRef: 'secretStoreRef: hiraya-dev-secrets-manager' },
      { id: 'kubernetes-secret', label: 'Kubernetes Secret', owner: 'External Secrets Operator', mechanism: 'target creationPolicy: Owner', explanation: 'ESO 在 vintage namespace materialize runtime Secret，供需要 database credentials 或 connection material 的 workloads 使用。', sourceRef: 'target.name: vintage-secrets' },
      { id: 'runtime-consumers', label: 'Application Runtime services', owner: 'Application Runtime', mechanism: 'pod environment references', explanation: 'Application services 與 PostgreSQL workloads 在 runtime consume materialized Secret，而不把 values 存進 Git。' },
    ],
    nonClaims: [
      '這張圖刻意只解釋 materialization，不展示 secret values 或 individual keys。',
      'refreshInterval: 1h 是 reconciliation behavior，不是 rotation guarantee。',
      '這個視圖示範 runtime materialization；automated rotation 與 production-grade audit hardening 仍是 future work。',
    ],
  },
}
