import type { ArchitectureOwnershipContent } from './architectureOwnership'

export const architectureOwnershipContentZhTW: ArchitectureOwnershipContent = {
  routeId: 'arch',
  title: '把架構先設計成清楚的 Ownership Boundaries',
  summary:
    'Hiraya 先用權責邊界解釋架構：Delivery 提出並證明變更，AWS 提供可重建的基礎，GitOps 管理平台能力並開放被選定的 Runtime Path，Observation 則把結果回饋到決策迴圈。',
  chrome: {
    eyebrow: 'Ownership explorer',
    boundaryStackLabel: '權責堆疊',
    ownerLabel: 'Owner',
    selectedBoundaryLabel: '已選擇的邊界',
    primaryOwnerLabel: '主要 Owner',
    responsibilityLabel: '責任範圍',
    designDecisionLabel: '設計決策',
    ownedLayersLabel: '擁有／控制的層',
    supportingMechanismsLabel: '支撐機制',
    doesNotOwnLabel: '刻意不負責',
    boundaryStackAriaSuffix: '權責堆疊',
  },
  boundaries: [
    {
      id: 'delivery-authority',
      label: 'Delivery Authority',
      shortLabel: 'Authority',
      primaryOwner: 'GitHub Actions + human review',
      supportingMechanisms: ['protected branches', 'pull request checks', 'environment approvals', 'OIDC federation', 'promotion pull requests'],
      layers: [
        { id: 'protected-git-branches', label: 'Protected Git branches', brief: '定義 Accepted Desired State 可以進入的位置。' },
        { id: 'pull-request-checks', label: 'Pull request checks', brief: '在 merge 前產生驗證證據。' },
        { id: 'image-publishing-workflow', label: 'Image publishing workflow', brief: '把已接受的程式碼轉成有標籤的 artifact。' },
        { id: 'manifest-promotion-pr', label: 'Manifest promotion PR', brief: '提出 Runtime Desired State 變更。' },
        { id: 'infrastructure-approval-gate', label: 'Infrastructure approval gate', brief: '把高權限 apply 與一般交付分開。' },
      ],
      responsibility: '控制 application 與 infrastructure 變更如何被提出、驗證、核准，並交給擁有 runtime 或 cloud state 的邊界。',
      decision: 'CI 負責產生證據與 proposed desired-state changes；它不直接變成不受限制的 runtime authority。',
      doesNotOwn: ['cluster runtime convergence', 'public route exposure', 'workload business behavior', 'cloud resources after apply'],
    },
    {
      id: 'aws-foundation',
      label: 'AWS Foundation',
      shortLabel: 'AWS',
      primaryOwner: 'Terraform platform-core',
      supportingMechanisms: ['AWS managed services', 'remote Terraform state', 'IAM and IRSA policies', 'environment-gated infrastructure workflow'],
      layers: [
        { id: 'terraform-platform-core', label: 'Terraform platform-core', brief: '表達可重建的 cloud intent。' },
        { id: 'eks-control-plane', label: 'EKS control plane', brief: '提供 managed Kubernetes substrate。' },
        { id: 'managed-node-group', label: 'Managed node group', brief: '提供 disposable worker capacity。' },
        { id: 'vpc-subnets-nat', label: 'VPC / subnets / NAT', brief: '定義網路放置位置與 egress 邊界。' },
        { id: 'iam-irsa', label: 'IAM / IRSA', brief: '限制 automation 與 service account 的 AWS 存取。' },
        { id: 'ecr-secrets-manager', label: 'ECR / Secrets Manager', brief: '保存 artifacts 與外部化 secret source。' },
      ],
      responsibility: '提供其他 ownership boundaries 依賴的 AWS substrate。',
      decision: '維持 dev platform 可重建，同時把 durable bootstrap concerns 與 disposable platform core 分開。',
      doesNotOwn: ['application image contents', 'Kubernetes workload desired state', 'service rollout health', 'public visitor behavior'],
    },
    {
      id: 'cluster-platform',
      label: 'Cluster Platform',
      shortLabel: 'Cluster',
      primaryOwner: 'Argo CD platform applications',
      supportingMechanisms: ['App-of-Apps root application', 'Argo CD platform Applications', 'Kubernetes controllers', 'Helm/Kustomize manifests', 'namespace-level platform resources', 'sync-wave ordering'],
      layers: [
        { id: 'argocd-platform-apps', label: 'Argo CD apps', brief: '從 Git 持續 reconcile shared platform capabilities。' },
        { id: 'platform-namespaces', label: 'Platform namespaces', brief: '建立共享的 operation 與 route-admission 邊界。' },
        { id: 'gateway-api-crds', label: 'Gateway API CRDs', brief: '定義 cluster routing vocabulary。' },
        { id: 'aws-load-balancer-controller', label: 'AWS LBC', brief: '把 Gateway intent 轉成 ALB 與 target groups。' },
        { id: 'external-dns', label: 'ExternalDNS', brief: '把已核准 route hostnames 發佈到 Route 53。' },
        { id: 'external-secrets', label: 'External Secrets', brief: '把 allowlisted AWS secrets materialize 到 Kubernetes。' },
        { id: 'cert-storage-monitoring', label: 'Certs / storage / metrics', brief: '提供 cert-manager、gp3 storage、Prometheus 與 Grafana 能力。' },
      ],
      responsibility: '提供讓 workloads 可被觸達、可觀測、可操作的 shared in-cluster capabilities。',
      decision: 'Platform add-ons 由 GitOps 管理，而不是 cluster 建好後手動安裝。',
      doesNotOwn: ['AWS substrate provisioning', 'application release approval', 'public exposure policy as a portfolio concept', 'business service behavior'],
    },
    {
      id: 'public-edge',
      label: 'Public Edge',
      shortLabel: 'Edge',
      primaryOwner: 'Shared Gateway + service-owned routes',
      supportingMechanisms: ['Route 53', 'ACM', 'shared ALB', 'Gateway API', 'namespace route admission', 'service-owned HTTPRoutes', 'ExternalDNS'],
      layers: [
        { id: 'public-dns-names', label: 'Public DNS', brief: '定義可被訪問的 hostnames。' },
        { id: 'acm-certificate', label: 'ACM cert', brief: '終止可信任的 HTTPS。' },
        { id: 'shared-alb', label: 'Shared ALB', brief: '集中管理 public ingress。' },
        { id: 'shared-gateway', label: 'Shared Gateway', brief: '接受已核准 public namespaces 的 routes。' },
        { id: 'service-owned-routes', label: 'Service HTTPRoutes', brief: '讓 Vintage、Grafana 與 Argo CD access 擁有自己的 route intent。' },
      ],
      responsibility: '控制 shared public HTTPS boundary 與 route-admission policy，同時讓各 service owner 宣告自己的 public route。',
      decision: '使用一個 shared Gateway 搭配 namespace admission，而不是每個服務各自建立 public LoadBalancer，或由中央團隊擁有所有 HTTPRoute。',
      doesNotOwn: ['private backend service logic', 'image publishing', 'secret source values', 'service-specific route intent'],
    },
    {
      id: 'application-runtime',
      label: 'Application Runtime',
      shortLabel: 'Runtime',
      primaryOwner: 'Argo CD workload application + Kubernetes controllers',
      supportingMechanisms: ['Deployments', 'Services', 'StatefulSet', 'ConfigMaps/Secrets materialized into Kubernetes', 'rollout controllers'],
      layers: [
        { id: 'vintage-workload-manifests', label: 'Vintage workload manifests', brief: '宣告 desired runtime state。' },
        { id: 'frontend-deployment', label: 'Frontend deployment', brief: '服務 Storefront 與 same-origin API proxy。' },
        { id: 'gateway-backend-services', label: 'Gateway/backend services', brief: '執行 private API boundaries。' },
        { id: 'clusterip-services', label: 'ClusterIP services', brief: '讓 internal service-to-service access 維持私有。' },
        { id: 'postgresql-statefulset-pvc', label: 'PostgreSQL StatefulSet/PVC', brief: '提供 disposable dev data persistence。' },
        { id: 'kubernetes-rollout-control', label: 'Kubernetes rollout control', brief: '讓 pods 收斂到 declared state。' },
      ],
      responsibility: '在 public edge 後方執行 Hiraya workloads，同時保持 service internals private。',
      decision: '分離 public storefront exposure 與 private backend execution，並讓 runtime state 由 GitOps 擁有。',
      doesNotOwn: ['cloud foundation creation', 'public DNS/certificate ownership', 'CI approval policy', 'observability interpretation'],
    },
    {
      id: 'observation',
      label: 'Observation',
      shortLabel: 'Observe',
      primaryOwner: 'Operational feedback surfaces',
      supportingMechanisms: ['Prometheus', 'Grafana', 'smoke tests', 'Kubernetes health signals', 'release evidence'],
      layers: [
        { id: 'prometheus-metrics', label: 'Prometheus metrics', brief: '收集 service 與 cluster signals。' },
        { id: 'grafana-dashboard', label: 'Grafana dashboard', brief: '把 metrics 轉成可檢視的 service health。' },
        { id: 'smoke-checks', label: 'Smoke checks', brief: '交付後驗證 public behavior。' },
        { id: 'argocd-health-state', label: 'Argo CD health state', brief: '回報 convergence 與 sync status。' },
        { id: 'release-evidence', label: 'Release evidence', brief: '把 runtime result 連回 delivery decisions。' },
      ],
      responsibility: '用 feedback 與 verification signals 解釋 runtime 和 release decisions 是否有效。',
      decision: '把 observability 當成 portfolio explanation 的一部分，而不只是安裝 monitoring tools。',
      doesNotOwn: ['workload deployment authority', 'AWS infrastructure provisioning', 'public route publication', 'business feature decisions'],
    },
  ],
  connectors: [
    { from: 'delivery-authority', to: 'aws-foundation', label: '提出／核准變更' },
    { from: 'aws-foundation', to: 'cluster-platform', label: '提供 cloud substrate' },
    { from: 'cluster-platform', to: 'public-edge', label: '啟用 cluster capabilities' },
    { from: 'public-edge', to: 'application-runtime', label: '開放被選定的 routes' },
    { from: 'application-runtime', to: 'observation', label: '送出 runtime signals' },
  ],
}
