import type { BriefPlatformProofMapContent } from './briefPlatformProofMap'

export const briefPlatformProofMapContentEn = {
  eyebrow: 'Platform Proof Map',
  title: 'One map from source authority to public proof',
  summary:
    'The Brief route uses this graph to show why Hiraya is a rebuildable dev-platform demonstration rather than a static page or isolated app demo.',
  mapClaim:
    'Reviewed source changes can become artifacts, accepted GitOps desired state, EKS workloads, public HTTPS behavior, and observable evidence without making manual cluster mutation the default story.',
  zones: [
    {
      id: 'source-delivery',
      label: 'Source and delivery authority',
      shortLabel: 'Source',
      summary: 'Where changes are proposed, checked, and approved before they touch cloud or cluster state.',
      posture: 'reviewed change authority',
      position: { x: 0, y: 0 },
      size: { width: 1480, height: 120 },
    },
    {
      id: 'project-bootstrap',
      label: 'Project Bootstrap',
      shortLabel: 'Bootstrap',
      summary: 'Small durable layer that survives EKS rebuilds: state, federation, artifacts, and external secrets.',
      posture: 'retained foundations',
      position: { x: 0, y: 135 },
      size: { width: 1480, height: 120 },
    },
    {
      id: 'platform-proof',
      label: 'Platform, runtime behavior, and proof surfaces',
      shortLabel: 'Platform proof',
      summary: 'One flexible lane shows AWS networking, EKS controllers, compact workload behavior, and proof surfaces together.',
      posture: 'AWS ↔ EKS ↔ proof',
      position: { x: 0, y: 270 },
      size: { width: 1480, height: 510 },
    },
  ],
  nodes: [
    {
      id: 'repo-change',
      zoneId: 'source-delivery',
      label: 'Repository change',
      detail: 'Application, GitOps, or infrastructure intent starts as reviewed source instead of a console mutation.',
      code: 'git',
      kind: 'actor',
      role: 'authority',
      posture: 'reviewable source',
      toolIcon: 'github',
      position: { x: 30, y: 45 },
      sourceRefs: ['.github/workflows/app-pr-baseline.yml', 'docs/portfolio/PROJECT_BRIEF.md'],
    },
    {
      id: 'github-actions',
      zoneId: 'source-delivery',
      label: 'GitHub Actions',
      detail: 'Runs validation, image CI, promotion, infra apply/destroy, and deployment smoke evidence with scoped authority.',
      code: 'ci',
      kind: 'stage',
      role: 'authority',
      posture: 'automation boundary',
      toolIcon: 'github-actions',
      position: { x: 250, y: 45 },
      sourceRefs: ['.github/workflows/image-ci.yml', '.github/workflows/infra-deploy.yml', '.github/workflows/deploy-smoke.yml'],
    },
    {
      id: 'validation-evidence',
      zoneId: 'source-delivery',
      label: 'Validation evidence',
      detail: 'Pull request and workflow checks create proof before privileged cloud write paths are used.',
      code: 'checks',
      kind: 'evidence',
      role: 'proof',
      posture: 'pre-change proof',
      position: { x: 470, y: 45 },
      sourceRefs: ['.github/workflows/app-pr-baseline.yml', 'docs/evidence-checklist.md'],
    },
    {
      id: 'manifest-pr',
      zoneId: 'source-delivery',
      label: 'Manifest promotion PR',
      detail: 'Image CI proposes a GitOps manifest change; reviewed Git remains the accepted desired-state gate.',
      code: 'pr',
      kind: 'gate',
      role: 'authority',
      posture: 'review gate',
      position: { x: 690, y: 45 },
      sourceRefs: ['.github/workflows/image-ci.yml', 'gitops/apps/vintage/'],
    },
    {
      id: 'accepted-gitops',
      zoneId: 'source-delivery',
      label: 'Accepted GitOps state',
      detail: 'The desired runtime state is accepted in Git before Argo CD reconciles the cluster.',
      code: 'gitops',
      kind: 'artifact',
      role: 'authority',
      posture: 'desired state',
      position: { x: 910, y: 45 },
      sourceRefs: ['gitops/clusters/dev/root/applications/', 'gitops/apps/vintage/'],
    },
    {
      id: 'infra-approval',
      zoneId: 'source-delivery',
      label: 'Infrastructure approval',
      detail: 'Terraform apply/destroy is separated from normal application delivery with environment-gated authority.',
      code: 'tf gate',
      kind: 'gate',
      role: 'authority',
      posture: 'high-permission gate',
      toolIcon: 'terraform',
      position: { x: 1130, y: 45 },
      sourceRefs: ['.github/workflows/infra-deploy.yml', '.github/workflows/infra-destroy.yml'],
    },
    {
      id: 'terraform-state',
      zoneId: 'project-bootstrap',
      label: 'Terraform state access',
      detail: 'Remote state and bootstrap permissions are durable enough to recreate the disposable platform consistently.',
      code: 'state',
      kind: 'artifact',
      role: 'authority',
      posture: 'durable',
      toolIcon: 'terraform',
      position: { x: 30, y: 180 },
      sourceRefs: ['infra/envs/dev/bootstrap/'],
    },
    {
      id: 'oidc-roles',
      zoneId: 'project-bootstrap',
      label: 'GitHub OIDC roles',
      detail: 'Federated CI roles avoid long-lived cloud credentials while allowing scoped automation.',
      code: 'oidc',
      kind: 'gate',
      role: 'authority',
      posture: 'durable trust',
      position: { x: 360, y: 180 },
      sourceRefs: ['infra/envs/dev/bootstrap/data.tf', 'infra/envs/dev/bootstrap/main.tf'],
    },
    {
      id: 'ecr-repositories',
      zoneId: 'project-bootstrap',
      label: 'ECR repositories',
      detail: 'Durable artifact storage sits outside the disposable EKS runtime; nodes pull images from ECR during rollout.',
      code: 'ecr',
      kind: 'artifact',
      role: 'authority',
      posture: 'durable artifacts',
      toolIcon: 'aws-ecr',
      position: { x: 690, y: 180 },
      sourceRefs: ['infra/modules/ecr/', '.github/workflows/image-ci.yml'],
    },
    {
      id: 'secrets-manager',
      zoneId: 'project-bootstrap',
      label: 'Secrets Manager',
      detail: 'Externalized secret sources survive cluster rebuilds and are materialized into Kubernetes by controller intent.',
      code: 'secrets',
      kind: 'environment',
      role: 'authority',
      posture: 'durable secret source',
      toolIcon: 'aws-secrets-manager',
      position: { x: 1020, y: 180 },
      sourceRefs: ['infra/modules/platform-admin-secrets/', 'gitops/platform/external-secrets/'],
    },
    {
      id: 'platform-core',
      zoneId: 'platform-proof',
      label: 'Platform Core',
      detail: 'Terraform-owned cloud substrate: VPC, subnets, EKS, IAM, IRSA, Route 53/ACM prerequisites, and worker capacity.',
      code: 'tf core',
      kind: 'environment',
      role: 'runtime',
      posture: 'cloud substrate',
      toolIcon: 'terraform',
      position: { x: 30, y: 315 },
      sourceRefs: ['infra/envs/dev/platform-core/', 'infra/modules/vpc/', 'infra/modules/eks/'],
    },
    {
      id: 'vpc-network',
      zoneId: 'platform-proof',
      label: 'VPC network',
      detail: 'Public subnets host load-balancing entry points while private subnets host EKS nodes; NAT and the S3 Gateway Endpoint support controlled egress.',
      code: 'vpc',
      kind: 'environment',
      role: 'runtime',
      posture: 'public/private split',
      toolIcon: 'aws-vpc',
      position: { x: 282, y: 315 },
      sourceRefs: ['infra/modules/vpc/', 'infra/envs/dev/platform-core/'],
    },
    {
      id: 'eks-node-group',
      zoneId: 'platform-proof',
      label: 'EKS node group',
      detail: 'Managed worker nodes run in private subnets, pull workload images from ECR, and receive AWS access through scoped node and IRSA policies.',
      code: 'eks nodes',
      kind: 'system',
      role: 'runtime',
      posture: 'private compute',
      toolIcon: 'aws-eks',
      position: { x: 534, y: 315 },
      sourceRefs: ['infra/modules/eks/', 'infra/envs/dev/platform-core/'],
    },
    {
      id: 'cluster-bootstrap',
      zoneId: 'platform-proof',
      label: 'Cluster Bootstrap',
      detail: 'Terraform/Helm handoff installs Argo CD, AppProjects, and the root app so GitOps can take over.',
      code: 'handoff',
      kind: 'stage',
      role: 'authority',
      posture: 'bootstrap handoff',
      toolIcon: 'kubernetes',
      position: { x: 30, y: 500 },
      sourceRefs: ['infra/envs/dev/cluster-bootstrap/', 'gitops/clusters/dev/root/applications/'],
    },
    {
      id: 'argocd',
      zoneId: 'platform-proof',
      label: 'Argo CD',
      detail: 'Pulls accepted Git desired state and reconciles platform and workload resources; it does not pull images from ECR.',
      code: 'git pull',
      kind: 'system',
      role: 'authority',
      posture: 'GitOps reconciler',
      toolIcon: 'argo-cd',
      position: { x: 282, y: 500 },
      sourceRefs: ['gitops/clusters/dev/root/applications/'],
    },
    {
      id: 'cluster-platform',
      zoneId: 'platform-proof',
      label: 'Cluster Platform',
      detail: 'Shared add-ons provide the EKS-to-AWS bridge: Gateway API, AWS Load Balancer Controller, ExternalDNS, External Secrets Operator, monitoring, and storage.',
      code: 'addons',
      kind: 'system',
      role: 'runtime',
      posture: 'shared capabilities',
      toolIcon: 'kubernetes',
      position: { x: 534, y: 500 },
      sourceRefs: ['gitops/platform/edge/', 'gitops/platform/external-dns/', 'gitops/platform/external-secrets/', 'gitops/platform/monitoring/'],
    },
    {
      id: 'aws-network-bridge',
      zoneId: 'platform-proof',
      label: 'AWS controllers',
      detail: 'AWS Load Balancer Controller turns Gateway/Service intent into ALB resources; ExternalDNS writes Route 53 records; IRSA scopes AWS API calls from service accounts.',
      code: 'k8s → aws',
      kind: 'gate',
      role: 'runtime',
      posture: 'controller bridge',
      toolIcon: 'aws',
      position: { x: 786, y: 315 },
      sourceRefs: ['gitops/platform/edge/', 'gitops/platform/external-dns/', 'infra/envs/dev/platform-core/'],
    },
    {
      id: 'public-edge',
      zoneId: 'platform-proof',
      label: 'Public Edge',
      detail: 'Platform Core prepares Route 53 and ACM prerequisites; GitOps Gateway/HTTPRoute intent plus AWS controllers publish selected HTTPS paths into EKS workloads.',
      code: 'dns/tls/alb',
      kind: 'gate',
      role: 'runtime',
      posture: 'public boundary',
      toolIcon: 'aws-route53-alb',
      position: { x: 1038, y: 315 },
      sourceRefs: ['gitops/platform/edge/', 'gitops/apps/vintage/'],
    },
    {
      id: 'prometheus-metrics',
      zoneId: 'platform-proof',
      label: 'Prometheus metrics',
      detail: 'Cluster monitoring records selected gateway/workload and platform signals that Grafana can present as release feedback.',
      code: 'metrics',
      kind: 'system',
      role: 'proof',
      posture: 'monitoring backend',
      toolIcon: 'prometheus',
      position: { x: 1290, y: 585 },
      sourceRefs: ['gitops/platform/monitoring/'],
    },
    {
      id: 'aws-service-bridges',
      zoneId: 'platform-proof',
      label: 'AWS service bridges',
      detail: 'EKS reaches durable AWS services through explicit mechanisms: ECR image pulls, Secrets Manager reads through External Secrets, Route 53 updates through ExternalDNS, and ALB reconciliation through the load-balancer controller.',
      code: 'aws APIs',
      kind: 'system',
      role: 'runtime',
      posture: 'explicit integrations',
      toolIcon: 'aws',
      position: { x: 786, y: 500 },
      sourceRefs: ['infra/modules/ecr/', 'gitops/platform/external-secrets/', 'gitops/platform/external-dns/'],
    },
    {
      id: 'portfolio-visitor',
      zoneId: 'platform-proof',
      label: 'Portfolio visitor',
      detail: 'Reviewer or user who validates the public Storefront behavior through HTTPS without receiving operational access.',
      code: 'user',
      kind: 'actor',
      role: 'proof',
      posture: 'public client',
      position: { x: 1290, y: 315 },
      sourceRefs: ['docs/evidence-checklist.md#p0-public-ingress'],
    },
    {
      id: 'storefront-endpoint',
      zoneId: 'platform-proof',
      label: 'hiraya.noidilin.dev',
      detail: 'Public Storefront endpoint proves the selected route, DNS, TLS, ingress, and workload path are reachable.',
      code: 'https',
      kind: 'evidence',
      role: 'proof',
      posture: 'public proof',
      position: { x: 1290, y: 405 },
      sourceRefs: ['docs/evidence-checklist.md#p0-public-ingress'],
    },
    {
      id: 'vintage-workload',
      zoneId: 'platform-proof',
      label: 'Vintage workload',
      detail: 'Compact proof that the platform runs a real application path. Internal microservice details are intentionally summarized here and expanded on the Architecture route.',
      code: 'vintage',
      kind: 'system',
      role: 'runtime',
      posture: 'application behavior',
      toolIcon: 'kubernetes',
      position: { x: 534, y: 405 },
      sourceRefs: ['gitops/apps/vintage/'],
    },
    {
      id: 'private-runtime',
      zoneId: 'platform-proof',
      label: 'Private services',
      detail: 'Gateway, auth, product, and orders are represented as a private runtime cluster rather than a full topology copy.',
      code: 'ClusterIP',
      kind: 'system',
      role: 'runtime',
      posture: 'private runtime',
      toolIcon: 'kubernetes',
      position: { x: 786, y: 405 },
      sourceRefs: ['gitops/apps/vintage/'],
    },
    {
      id: 'runtime-state',
      zoneId: 'platform-proof',
      label: 'Runtime state',
      detail: 'vintage-postgres and materialized runtime dependencies prove the workload has state and backing services without making service internals the Brief-level focus.',
      code: 'db + refs',
      kind: 'environment',
      role: 'runtime',
      posture: 'private data',
      toolIcon: 'postgres',
      position: { x: 1038, y: 405 },
      sourceRefs: ['gitops/apps/vintage/'],
    },
    {
      id: 'vintage-secrets',
      zoneId: 'platform-proof',
      label: 'vintage-secrets',
      detail: 'Kubernetes secret materialized from AWS Secrets Manager by External Secrets Operator; values are not exposed in the portfolio.',
      code: 'secret',
      kind: 'artifact',
      role: 'runtime',
      posture: 'materialized reference',
      toolIcon: 'aws-secrets-manager',
      position: { x: 786, y: 610 },
      sourceRefs: ['gitops/platform/external-secrets/', 'gitops/apps/vintage/'],
    },
    {
      id: 'operations-evidence',
      zoneId: 'platform-proof',
      label: 'Ops evidence',
      detail: 'Argo CD app health and Grafana dashboards are dev/demo operations surfaces, not customer-facing Storefront paths.',
      code: 'ops',
      kind: 'evidence',
      role: 'proof',
      posture: 'health + dashboards',
      toolIcon: 'grafana',
      position: { x: 1290, y: 675 },
      sourceRefs: ['docs/evidence-checklist.md#p0-argocd-app-of-apps', 'docs/evidence-checklist.md#p1-grafana'],
    },
    {
      id: 'smoke-evidence',
      zoneId: 'platform-proof',
      label: 'Smoke evidence',
      detail: 'Smoke checks prove the public path after rollout and connect delivery automation to observable runtime behavior.',
      code: 'smoke',
      kind: 'evidence',
      role: 'proof',
      posture: 'release proof',
      position: { x: 1290, y: 495 },
      sourceRefs: ['.github/workflows/deploy-smoke.yml', 'docs/evidence-checklist.md#p0-public-ingress'],
    },
  ],
  edges: [
    { id: 'repo-actions', source: 'repo-change', target: 'github-actions', label: 'triggers', lensIds: ['delivery-gitops'] },
    { id: 'actions-validation', source: 'github-actions', target: 'validation-evidence', label: 'checks', lensIds: ['delivery-gitops'] },
    { id: 'actions-ecr', source: 'github-actions', target: 'ecr-repositories', label: 'image push', lensIds: ['delivery-gitops'] },
    { id: 'actions-manifest-pr', source: 'github-actions', target: 'manifest-pr', lensIds: ['delivery-gitops'] },
    { id: 'manifest-accepted', source: 'manifest-pr', target: 'accepted-gitops', label: 'reviewed', lensIds: ['delivery-gitops'] },
    { id: 'accepted-argocd', source: 'accepted-gitops', target: 'argocd', label: 'pulls Git', lensIds: ['delivery-gitops', 'rebuild-destroy'] },
    { id: 'argocd-workload', source: 'argocd', target: 'vintage-workload', lensIds: ['delivery-gitops'] },
    { id: 'ecr-workload', source: 'ecr-repositories', target: 'vintage-workload', lensIds: ['delivery-gitops'] },
    { id: 'workload-smoke', source: 'vintage-workload', target: 'smoke-evidence', label: 'smoke', lensIds: ['delivery-gitops'] },
    { id: 'infra-oidc', source: 'oidc-roles', target: 'infra-approval', label: 'OIDC trust', lensIds: ['rebuild-destroy'] },
    { id: 'state-core', source: 'terraform-state', target: 'platform-core', label: 'state-backed', lensIds: ['rebuild-destroy'] },
    { id: 'approval-core', source: 'infra-approval', target: 'platform-core', label: 'apply', lensIds: ['rebuild-destroy'] },
    { id: 'core-vpc', source: 'platform-core', target: 'vpc-network', label: 'network', lensIds: ['visitor-request', 'rebuild-destroy'] },
    { id: 'vpc-nodes', source: 'vpc-network', target: 'eks-node-group', label: 'nodes', lensIds: ['visitor-request', 'rebuild-destroy'] },
    { id: 'nodes-workload', source: 'eks-node-group', target: 'vintage-workload', label: 'runs pods', lensIds: ['visitor-request'] },
    { id: 'core-bootstrap', source: 'platform-core', target: 'cluster-bootstrap', label: 'cluster ready', lensIds: ['rebuild-destroy'] },
    { id: 'bootstrap-argocd', source: 'cluster-bootstrap', target: 'argocd', label: 'root app', lensIds: ['rebuild-destroy'] },
    { id: 'argocd-platform', source: 'argocd', target: 'cluster-platform', label: 'add-ons', lensIds: ['rebuild-destroy', 'operations-evidence'] },
    { id: 'platform-controllers', source: 'cluster-platform', target: 'aws-network-bridge', label: 'controllers', lensIds: ['visitor-request', 'rebuild-destroy'] },
    { id: 'controllers-edge', source: 'aws-network-bridge', target: 'public-edge', label: 'ALB', lensIds: ['visitor-request'] },
    { id: 'controllers-services', source: 'cluster-platform', target: 'aws-service-bridges', label: 'APIs', lensIds: ['rebuild-destroy'] },
    { id: 'bridge-secrets', source: 'secrets-manager', target: 'aws-service-bridges', lensIds: ['rebuild-destroy'] },
    { id: 'service-bridges-secrets', source: 'aws-service-bridges', target: 'vintage-secrets', label: 'materializes', lensIds: ['rebuild-destroy'] },
    { id: 'public-storefront', source: 'public-edge', target: 'storefront-endpoint', label: 'HTTPS', lensIds: ['visitor-request'] },
    { id: 'visitor-storefront', source: 'portfolio-visitor', target: 'storefront-endpoint', label: 'opens URL', lensIds: ['visitor-request'] },
    { id: 'storefront-workload', source: 'storefront-endpoint', target: 'vintage-workload', label: 'routes', lensIds: ['visitor-request'] },
    { id: 'workload-private', source: 'vintage-workload', target: 'private-runtime', lensIds: ['visitor-request'] },
    { id: 'private-state', source: 'private-runtime', target: 'runtime-state', label: 'private data', lensIds: ['visitor-request'] },
    { id: 'secrets-private', source: 'vintage-secrets', target: 'private-runtime', label: 'env refs', lensIds: ['rebuild-destroy'] },
    { id: 'cluster-prometheus', source: 'cluster-platform', target: 'prometheus-metrics', label: 'metrics', lensIds: ['operations-evidence'] },
    { id: 'workload-metrics', source: 'vintage-workload', target: 'prometheus-metrics', label: 'signals', lensIds: ['operations-evidence'] },
    { id: 'prometheus-ops', source: 'prometheus-metrics', target: 'operations-evidence', label: 'dashboards', lensIds: ['operations-evidence'] },
    { id: 'argocd-ops', source: 'argocd', target: 'operations-evidence', lensIds: ['operations-evidence'] },
    { id: 'smoke-public', source: 'smoke-evidence', target: 'storefront-endpoint', label: 'public proof', lensIds: ['operations-evidence'] },
  ],
  lenses: [
    {
      id: 'visitor-request',
      label: 'Visitor request proof',
      summary: 'Trace public HTTPS through AWS networking into compact workload proof.',
      claim: 'Only the Storefront path is public; backend behavior remains behind the platform boundary.',
      highlightedNodeIds: [
        'portfolio-visitor',
        'vpc-network',
        'eks-node-group',
        'aws-network-bridge',
        'public-edge',
        'storefront-endpoint',
        'vintage-workload',
        'private-runtime',
        'runtime-state',
      ],
      evidenceRefs: ['p0-public-ingress'],
      nextRoute: 'arch',
    },
    {
      id: 'delivery-gitops',
      label: 'Delivery/GitOps proof',
      summary: 'Show CI artifact creation, reviewed Git desired state, Argo CD rollout, and smoke evidence.',
      claim: 'CI proposes and publishes; reviewed Git and Argo CD own accepted runtime state.',
      highlightedNodeIds: [
        'repo-change',
        'github-actions',
        'validation-evidence',
        'ecr-repositories',
        'manifest-pr',
        'accepted-gitops',
        'argocd',
        'vintage-workload',
        'smoke-evidence',
      ],
      evidenceRefs: ['p0-cicd-delivery-flow', 'p1-rollback-path'],
      nextRoute: 'sdlc',
    },
    {
      id: 'rebuild-destroy',
      label: 'Rebuild/destroy proof',
      summary: 'Separate retained bootstrap from disposable AWS/EKS and controller-managed service bridges.',
      claim: 'Expensive runtime is disposable; durable foundations preserve the ability to rebuild it.',
      highlightedNodeIds: [
        'terraform-state',
        'oidc-roles',
        'secrets-manager',
        'infra-approval',
        'platform-core',
        'vpc-network',
        'eks-node-group',
        'cluster-bootstrap',
        'argocd',
        'cluster-platform',
        'aws-network-bridge',
        'aws-service-bridges',
        'vintage-secrets',
      ],
      evidenceRefs: ['p0-infra-approval-gate', 'p2-cost-destroy-workflow', 'p1-secrets'],
      nextRoute: 'cost',
    },
    {
      id: 'operations-evidence',
      label: 'Operations evidence proof',
      summary: 'Connect monitoring, GitOps health, smoke checks, and public proof surfaces.',
      claim: 'Observability and GitOps health support the platform claim without becoming the whole explanation.',
      highlightedNodeIds: [
        'cluster-platform',
        'argocd',
        'prometheus-metrics',
        'vintage-workload',
        'operations-evidence',
        'smoke-evidence',
        'storefront-endpoint',
      ],
      evidenceRefs: ['p0-argocd-app-of-apps', 'p1-grafana'],
      nextRoute: 'waf',
    },
  ],
} as const satisfies BriefPlatformProofMapContent
