gateway:
  name: public
  className: aws-alb
loadBalancer:
  name: hiraya-dev-public
  certificateArn: ""
domains:
  root: hiraya.noidilin.dev
  wildcard: "*.hiraya.noidilin.dev"
allowedRoutes:
  namespaceLabelKey: hiraya.noidilin.dev/public-gateway-access
  namespaceLabelValue: "true"
