apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: vintage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 549475122024.dkr.ecr.ap-northeast-1.amazonaws.com/hiraya-product-service:0dda4db99c80e13340a4c5a0a23e9b323a3cb423
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3003"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vintage-secrets
                  key: PRODUCTS_DB_URL

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: vintage
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
