apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hiraya-platform
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.20.3
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/gitops/platform/cert-manager/values-dev.yaml
    - repoURL: https://github.com/noidilin/hiraya.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
