apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hiraya-platform
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 56.21.0
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/gitops/platform/monitoring/values-dev.yaml
    - repoURL: https://github.com/noidilin/hiraya.git
      targetRevision: refactor/gitops-refactor
      path: gitops/platform/monitoring
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
