apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hiraya-platform
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.10.7
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/gitops/platform/external-secrets/values-dev.yaml
    - repoURL: https://github.com/noidilin/hiraya.git
      targetRevision: main
      path: gitops/platform/external-secrets
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
