apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gateway-api-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hiraya-platform
  source:
    repoURL: https://github.com/noidilin/hiraya.git
    targetRevision: refactor/gitops-refactor
    path: gitops/platform/gateway-api-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
