apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vintage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hiraya-workloads
  source:
    repoURL: https://github.com/noidilin/hiraya.git
    targetRevision: refactor/gitops-refactor
    path: gitops/apps/vintage
  destination:
    server: https://kubernetes.default.svc
    namespace: vintage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
