mock_provider "kubernetes" {}
mock_provider "helm" {}
mock_provider "random" {}

run "applies_public_grafana_route_without_public_prometheus" {
  command = apply

  variables {
    grafana_hostname                  = "grafana.example.test"
    gateway_name                      = "public"
    gateway_namespace                 = "edge"
    public_gateway_access_label_key   = "example.test/public-gateway-access"
    public_gateway_access_label_value = "true"
  }

  assert {
    condition     = kubernetes_namespace_v1.monitoring.metadata[0].labels["example.test/public-gateway-access"] == "true"
    error_message = "Monitoring namespace must carry the approved public Gateway access label."
  }

  assert {
    condition     = random_password.grafana_admin.length >= 32 && random_password.grafana_admin.special == true
    error_message = "Grafana admin password must be strongly generated by Terraform."
  }

  assert {
    condition     = yamldecode(helm_release.monitoring.values[0]).grafana.service.type == "ClusterIP" && yamldecode(helm_release.monitoring.values[0]).grafana.adminPassword == random_password.grafana_admin.result
    error_message = "Grafana must stay internal and use the generated admin password."
  }

  assert {
    condition     = yamldecode(helm_release.monitoring.values[0]).prometheus.service.type == "ClusterIP"
    error_message = "Prometheus service must remain private as ClusterIP."
  }

  assert {
    condition     = helm_release.grafana_route.name == "grafana-admin-route" && yamldecode(helm_release.grafana_route.values[0]).route.hostname == "grafana.example.test" && yamldecode(helm_release.grafana_route.values[0]).service.name == "kube-prometheus-stack-grafana"
    error_message = "Grafana HTTPRoute release must target the shared Gateway and Grafana service hostname."
  }
}
